Use of split & chunk function

In [1]:
import torch

import numpy as np

In [14]:
def split_x_into_chunks(x):
  return x.chunk(chunks=4, dim=0)

def split_y_into_chunks(x):
  return x.chunk(chunks=4)

def split_x_using_split(x):
  return x.split([5,3], dim=0)

def split_y_using_split(x):
  return x.split([4,6,6])



x=torch.full((8,5),10)
y=torch.arange(16)
t1=split_x_into_chunks(x)
t2=split_y_into_chunks(y)
t3=split_x_using_split(x)
t4=split_y_using_split(y)

print(t1)
print(t2)
print(t3)
print(t4)

(tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]]), tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]]), tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]]), tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]]))
(tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7]), tensor([ 8,  9, 10, 11]), tensor([12, 13, 14, 15]))
(tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]]), tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]]))
(tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7, 8, 9]), tensor([10, 11, 12, 13, 14, 15]))


In [9]:
y=torch.tensor(16)
y.dim

<function Tensor.dim>