**Exercise**
INput: Given a 1d list and 2d numpy array
make 4 functons:

* returns the 1d list as tensors
* returns the numpy array as tensors
* returns a tensor of shape 3x4
* returns a tensor of shape 4x5 with all values as 5




In [ ]:
import torch

In [4]:

import numpy as np

def for_list(A):
  return torch.tensor(A)

def for_array(A):
  return torch.tensor(A)

def func1():
  ten1=torch.ones(3,4)
  return ten1

def func2():
  ten1=torch.zeros(4,5)
  ten1=torch.full_like(ten1, 5)
  return ten1





A=[(1,2,3),(1,2,3)]
B=np.array([[1,2,3],[1,2,3]])
ten1=for_list(A)
print(ten1)
ten2=for_array(B)
print(ten2)
ten3=func1()
print(ten3)
ten4=func2()
print(ten4)

tensor([[1, 2, 3],
        [1, 2, 3]])
tensor([[1, 2, 3],
        [1, 2, 3]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]])
