In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.3.0+cu121
True


INitializng a tensor with various types

In [2]:
ftens=torch.tensor(([1,2,3],[4,5,6]))
stens=torch.tensor(([1,2,3],[4,5,6]))

atens=ftens+stens
print(atens)

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


In [3]:
sstens=ftens-stens
print(sstens)

tensor([[0, 0, 0],
        [0, 0, 0]])


In [4]:
print(sstens.size())

torch.Size([2, 3])


In [5]:
import numpy as np


In [7]:
list_ten=torch.tensor([1,2,3])
tup_ten=torch.tensor((1,2,3))
array_ten=torch.tensor(np.array([1,2,3]))
print(tup_ten)
print(list_ten)
print(array_ten)  #initilaizng a tensors and creating a tensore, the shape is 1D and the data assigned is given

tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [13]:
##creating a tensoor of speciifc shape, (1,2,3) means a 3 dimensional tensor
#(1,2) means 2D tensor with 1 row, 2 column
#.zero initialzied all values as zero, .ones as 1 and .empty as random
ten1=torch.empty(1,2,3)
ten2=torch.zeros(1)
ten3=torch.ones(1,2)
print(ten1)
print(ten2)
print(ten3)

tensor([[[ 7.8596e+16,  4.4046e-41, -5.0763e-26],
         [ 3.0646e-41,  4.4842e-44,  0.0000e+00]]])
tensor([0.])
tensor([[1., 1.]])


In [14]:
import random as rd

In [18]:
ten4=torch.rand(2,3)  #initlaze random values from in between 0 to 1
ten5=torch.randn(2)   #initilaaze random value from a normal distribution (mean = 0, standard deviation = 1).
ten6=torch.randint(0,4,(2,2)) #(low, high, size )
print(ten4)
print(ten5)
print(ten6)

tensor([[0.3040, 0.0855, 0.2620],
        [0.4168, 0.3657, 0.6159]])
tensor([-0.3124,  0.1982])
tensor([[2, 1],
        [2, 2]])


In [19]:
ten7=torch.ones_like(ten1)
print(ten7)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


Tensor Attributes

In [20]:
ten1.device  #to know wether the tensor is on cpu or gpu

device(type='cpu')

In [21]:
ten2.dtype  #to know the datatype

torch.float32

In [22]:
ten3.shape  #to know shape

torch.Size([2, 2])

In [23]:
ten4.ndim #to find out dimension

2

**Tensor Data Types**

In [24]:
ten8=torch.tensor([1,2,3,4,5],dtype=torch.int8)
ten8.dtype

torch.int8

In [25]:
ten9=torch.tensor([1,2,3,4,5],dtype=torch.float32)
ten9.dtype

torch.float32

In [26]:
ten10=torch.tensor([1,2,3,4,5],dtype=torch.int16)
ten10.dtype

torch.int16

In [30]:
#type casting
ten11=torch.tensor([1,2,3,4,5],dtype=torch.int8)
ten11=ten11.float()   #int() to ocnvert to int
ten11.dtype

torch.float32

CReating tensors from random samples

In [32]:
torch.rand(2,2) #creates random values on every run

tensor([[0.4094, 0.0333],
        [0.5116, 0.6010]])

In [36]:
#for static-ing the random values geenrated we will:
torch.manual_seed(111)
torch.rand(2,2)

tensor([[0.7156, 0.9140],
        [0.2819, 0.2581]])

In [37]:
#creating a tensor LIKE OTHER tensors
#.ones_like(tensor to copy)  all values ar einitilaized to 1 but the shape remains same
#.full_like(tensor to coy, int)  shape is same as the tensor we wanna copy but the values are of integer which we have clairified
#