In [1]:
import torch

import numpy as np

Workin with slicing

In [2]:
ten1= torch.tensor([1,2,3,4,5,6,7,8])
print(ten1)
print(ten1[4])   #at position 4, we have the element 5, it si returned as tensor
print(ten1[2].item())  #the element at position 2 is returned as a number

tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor(5)
3


In [3]:
print(ten1[2:5]) #index slicing simple

tensor([3, 4, 5])


In [4]:
ten2= torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
ten2[0,0:3]  #1st row, 0th, 1st, 2nd element

tensor([1, 2, 3])

In [5]:
ten2[ten2<10]

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
torch.stack((ten2,ten2))  #resulting tensor has an additional dimension as compared to the og

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]],

        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]]])

In [7]:
t1,t2,t3,t4=torch.unbind(ten2)   #the og tensor has been broken into mini tensors
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1, 2, 3, 4])
tensor([5, 6, 7, 8])
tensor([ 9, 10, 11, 12])
tensor([13, 14, 15, 16])


MATHSSSSSSS

In [8]:
#Basic Maths
t1=torch.tensor([1,2,3])
t2=torch.tensor([5,4,3])
t3=t1.add(t2)
t4=t2.sub(t1)
t5=t1.sub(t2)
t6=t1.mul(t2)
t7=t1.div(t2)
t8=t2.div(t1)
print("tensor1:")
print(t1)
print("tensor2:")
print(t2)
print("tensor3:")
print(t3)
print("tensor4:")
print(t4)
print("tensor5:")
print(t5)
print("tensor6:")
print(t6)
print("tensor7:")
print(t7)
print("tensor8:")
print(t8)

tensor1:
tensor([1, 2, 3])
tensor2:
tensor([5, 4, 3])
tensor3:
tensor([6, 6, 6])
tensor4:
tensor([4, 2, 0])
tensor5:
tensor([-4, -2,  0])
tensor6:
tensor([5, 8, 9])
tensor7:
tensor([0.2000, 0.5000, 1.0000])
tensor8:
tensor([5., 2., 1.])


In [9]:
#Reduction functions

In [13]:
ten2=torch.tensor([[1,1,1],[2,2,2],[3,3,3]])
ten2=ten2.float()
t21=torch.mean(ten2) #i was getting an error that ten2 was of type long and mean() needed a dtype of complex or float
t22=torch.mode(ten2)
t23=torch.median(ten2)
t24=torch.std(ten2)
print(t21)
print(t22)
print(t23)
print(t24)


tensor(2.)
torch.return_types.mode(
values=tensor([1., 2., 3.]),
indices=tensor([2, 2, 2]))
tensor(2.)
tensor(0.8660)


Linear Algebra

In [14]:
ten1=torch.tensor([1,2,3])
ten2=torch.tensor([4,5,6])
ten3= torch.matmul(ten1, ten2) #simple dot product
print(ten3)

tensor(32)


In [16]:
ten1=torch.tensor([[1,2],[5,6]])
ten2=torch.tensor([[4,6],[7,9]])
ten3= torch.matmul(ten1, ten2) #simple dot product
print(ten3)

tensor([[18, 24],
        [62, 84]])


In [19]:
#computing
ten1=torch.tensor([[1,2],[5,6],[3,2]])
ten2=torch.tensor([[4,6],[7,9]])
torch.linalg.multi_dot((ten1, ten2)) #simple dot product


tensor([[18, 24],
        [62, 84],
        [26, 36]])

torch.matmul is a function for matrix multiplication. It can handle both matrix-matrix and matrix-vector multiplications, but it only takes two matrices or tensors at a time.

torch.linalg.multi_dot is used for multiplying multiple matrices together in an optimal order to minimize computational cost.

In [22]:
#AUTOMATIC DIFFERENTIATION - AUTOGRAD
x=torch.autograd.Variable(torch.tensor([2.0]), requires_grad=True)
y=torch.autograd.Variable(torch.tensor([1.0]), requires_grad=True)
z=torch.autograd.Variable(torch.tensor([5.0]), requires_grad=True)

a=x-y
f=z*a
print("Final vlaue of f: " ,f)
f.backward()
print("Grdaient of x: ", x.grad)
print("Grdaient of y: ", y.grad)
print("Grdaient of z: ", z.grad)

Final vlaue of f:  tensor([5.], grad_fn=<MulBackward0>)
Grdaient of x:  tensor([5.])
Grdaient of y:  tensor([-5.])
Grdaient of z:  tensor([1.])
